### ISSUE TITLE
通过helm安装jenkins过程中遇到的问题（一）：无法自动分配存储pvc

### ISSUE THREAD

**Issue by Cloudzp** [Cloudzp/FAQ#1]
## 问题描述：
通过helm安装jenkins过程中，pod一直处于Init状态，pod事件显示pvc没有绑定；
## 问题分析：
问题由于jenkins的chart模板中定义的jenkins依赖一个外部存储，是使用pvc的方式自动分配的，但是自己搭建的k8s集群不能自动分配存储
## 解决办法：
手动修改pvc-yaml文件:
1. 删除旧的pvc实例
````
$ kubectl get pvc
NAME                     STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
orange-vulture-jenkins   Bound     jenkins-pv-nfs   5Gi        RWO            hostpath-tmp   2h
$kubectl delete pvc orange-vulture-jenkins

````
2.根据yaml创建新的pvc实例及pv实例：
pv.yaml
````
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-nfs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath-tmp

````
pvc.yaml
````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  name: orange-vulture-jenkins
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath-tmp
  volumeName: jenkins-pv-nfs
````

````
$ kubectl create -f pv.yaml pvc.yaml
````
